language: python
sudo: required
dist: xenial
matrix:
  include:
  - python: 3.6
    env: TOX_ENV=py36-
    addons:
      sauce_connect:
        username: jsfehler
  - python: 3.7
    env: TOX_ENV=py37
    addons:
      sauce_connect:
        username: jsfehler
  - python: 3.6
    env: TOX_ENV=flake8
install:
- pip install tox coveralls
script:
- tox -e $TOX_ENV
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
after_success:
- coveralls
